<?php

use Drupal\external_content\ExternalContentJsonApi;


/**
 * Implements hook_theme().
 */
function external_content_theme($existing, $type, $theme, $path) {

  $items = [
    'external_content' => [
      'variables' => [
        'data' => NULL,
        'source_id' => NULL,
        'source' => NULL,
      ],
      'template' => 'external-content',
      'base hook' => 'external_content'
    ],
  ];

  return $items;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function template_preprocess_external_content(&$variables) {
  /** @var \Drupal\external_content\Entity\ExternalContent $source */
  $source = $variables['source'];
  $site_url = ExternalContentJsonApi::getSiteFromUrl($source->getResource());
  $variables['external_url'] = ExternalContentJsonApi::getUrlFromEntity($variables['data']);
  $variables['external_link'] = ExternalContentJsonApi::getLinkFromEntity($variables['data']);
  $variables['external_site'] = $site_url;
  $variables['external_type'] = $variables["data"]["type"];

  $variables['attributes']['class'] = [
    'external-content',
    'external-content--'. $source->getId(),
    'external-content--'. $variables["data"]["type"],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function external_content_theme_suggestions_external_content(array $variables) {
  /** @var \Drupal\external_content\Entity\ExternalContent $source */
  $source = $variables['source'];
  $suggestions = [];
  $entity_type = str_replace('-', '_', $variables["data"]["type"]);
  $suggestions[] = 'external_content__' . $source->getId();
  $suggestions[] = 'external_content__' . $entity_type;

  return $suggestions;

}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
//function external_content_theme_suggestions_external_content_alter(array $variables) {}
