<?php

/**
 * @file
 * External Content module.
 */

use Drupal\external_content\ExternalContentJsonApi;

/**
 * Implements hook_theme().
 */
function external_content_theme($existing, $type, $theme, $path) {

  $items = [
    'external_content' => [
      'variables' => [
        'doc' => NULL,
        'response' => NULL,
        'source_id' => NULL,
        'source' => NULL,
      ],
      'template' => 'external-content',
    ],
  ];

  return $items;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function external_content_theme_suggestions_external_content(array $variables) {
  /** @var \Drupal\external_content\Entity\ExternalContentSource $source */
  $source = $variables['source'];
  $suggestions = [
    'external_content',
    'external_content__' . $source->getId(),
    'external_content__' . $source->getType(),
  ];
  return $suggestions;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function template_preprocess_external_content(&$variables) {
  /** @var \Drupal\external_content\Entity\ExternalContentSource $source */
  $source = $variables['source'];
  $plugin_id = $source->getType();

  $variables['attributes']['class'] = [
    'external-content',
    'external-content--' . $source->id(),
  ];

  // Only apply JsonApi-specific processing for jsonapi plugin types
  if (in_array($plugin_id, ['jsonapi', 'jsonapi_json'])) {
    $site_url = ExternalContentJsonApi::getSiteFromUrl($source->getResource());
    $variables['external_url'] = ExternalContentJsonApi::getUrlFromEntity($variables['doc']);
    $variables['external_link'] = ExternalContentJsonApi::getLinkFromEntity($variables['doc']);
    $variables['external_site'] = $site_url;
    $variables['external_type'] = $variables["doc"]["type"];

    $variables['attributes']['class'][] = 'external-content--' . $variables["doc"]["type"];
  }
}
