external_content.external_content_source.*:
  type: config_entity
  label: external_content_source
  mapping:
    type:
      type: string
      label: 'Type'
    id:
      type: string
      label: 'ID'
    resource:
      type: string
      label: 'Resource'
    term_resource:
      type: string
      label: 'Term Resource'
    term_field:
      type: string
      label: 'Term Field'
    includes:
      type: string
      label: 'Includes'
    cache_timeout:
      type: integer
      label: 'Cache Timeout'
    plugin_configuration:
      type: mapping
      label: 'Plugin Configuration'

field.field_settings.external_content_item:
  type: mapping
  label: ExternalContentItem field settings
  mapping:
    enabled_souces:
      type: array
      label: Enabled Sources

field.value.external_content_item:
  type: mapping
  label: Default value
  mapping:
    value:
      type: label
      label: Value

field.formatter.settings.external_content_preview:
  type: mapping
  label: ExternalContentPreview formatter settings
  mapping:
    limit:
      type: integer
      label: Limit

field.formatter.settings.external_content_template:
  type: mapping
  label: ExternalContentPreview formatter settings
  mapping:
    limit:
      type: integer
      label: Limit

field.formatter.settings.external_content_json:
  type: mapping
  label: ExternalContentPreview formatter settings
  mapping:
    limit:
      type: integer
      label: Limit

field.widget.settings.external_content_default:
  type: mapping
  label: 'External content default widget settings'
  mapping:
    allow_multiple_values:
      type: boolean
      label: 'Allow multiple values'
    enable_quantity:
      type: boolean
      label: 'Enable quantity selection'
    max_quantity:
      type: integer
      label: 'Maximum quantity'

